apiVersion: apps/v1
kind: Deployment
metadata:
  name: baza-danych
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baza-danych
  template:
    metadata:
      labels:
        app: baza-danych
    spec:
      containers:
        - name: baza-danych
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
          ports:
            - containerPort: 27017
