version: '3.9'
services:
  db:
    image: mongo:4.1.13
    container_name: db
    networks:
      - net_A
    volumes:
      - mongo-data:/data/db
    ports:
      - "27019:27017"

volumes:
  mongo-data:

networks:
  net_A:
