version: "3"

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - my_network

  web:
    image: nginx
    networks:
      - my_network
    ports:
      - "80:80"
    environment:
      DB_HOST: db
    depends_on:
      - db

networks:
  my_network:
