version: '3.8'
services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    networks:
      - mynetwork
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthcheck']
      interval: 30s
      timeout: 10s
      retries: 3
  mongodb:
    image: mongo:4.4
    restart: always
    volumes:
      - mongodb-data:/data/db
    networks:
      - mynetwork
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
networks:
  mynetwork:
volumes:
  mongodb-data:
